# Generated by Django 3.0.7 on 2023-07-22 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_animal', models.CharField(max_length=20, verbose_name='Type Of Pet')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'db_table': 'animal',
                'ordering': ['type_animal'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name Of Pet')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('type_food', models.CharField(max_length=20, verbose_name='type the food')),
                ('imagen', models.ImageField(null='TRUE', upload_to='pets')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.Animal')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'pet',
                'ordering': ['name', 'age'],
            },
        ),
    ]
