# Generated by Django 4.2.4 on 2023-08-05 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import pet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_animal', models.CharField(max_length=20, verbose_name='Type Of Pet')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'db_table': 'animal',
                'ordering': ['type_animal'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Of Pet')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('type_food', models.CharField(max_length=50, verbose_name='type the food')),
                ('image', models.ImageField(null=True, upload_to=functools.partial(pet.models.make_filepath, *('pets',), **{}))),
                ('color', models.CharField(max_length=50, verbose_name='Color Of Pet')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.animal')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'pet',
                'ordering': ['name', 'age'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('evolution', models.TextField()),
                ('size', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=functools.partial(pet.models.make_filepath, *('procedures',), **{}))),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_condiciones', to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('professional_name', models.CharField(max_length=100)),
                ('observation', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_medicos', to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_salud', to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('health_condition', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_salud', to='pet.pet')),
            ],
        ),
    ]
