# Generated by Django 3.0.7 on 2023-07-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pets'),
        ),
    ]
