# Generated by Django 4.2.4 on 2023-08-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
