# Generated by Django 3.0.7 on 2023-07-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20230722_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='other',
            field=models.CharField(default='SOME STRING', max_length=20, verbose_name='type the food'),
        ),
    ]
