# Generated by Django 3.0.7 on 2023-07-29 18:12

from django.db import migrations, models
import functools
import pet.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pet_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='other',
        ),
        migrations.AlterField(
            model_name='pet',
            name='imagen',
            field=models.ImageField(null=True, upload_to=functools.partial(pet.models.make_filepath, *('pets',), **{})),
        ),
    ]
