# Generated by Django 4.2.4 on 2023-08-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcondition',
            name='health_type_condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicatorshealth',
            name='indicator_type',
            field=models.CharField(choices=[('Weight', 'Weight'), ('Body temperature', 'Body temperature'), ('Heart rate', 'Heart rate'), ('Respiratory rate', 'Respiratory rate'), ('Activity level', 'Activity level'), ('Hydration level', 'Hydration level'), ('Mucous membrane color', 'Mucous membrane color'), ('Coat quality', 'Coat quality'), ('Food consumption', 'Food consumption'), ('Behavior', 'Behavior')], max_length=100),
        ),
    ]
